version: '3.8'

services:
  # Database Service
  mariadb:
    image: mariadb:10.6
    container_name: workshop_mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-admin}
      - MYSQL_DATABASE=${DB_NAME:-universal_workshop}
      - MYSQL_USER=${DB_USER:-frappe}
      - MYSQL_PASSWORD=${DB_PASSWORD:-frappe}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./config/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - workshop_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis Cache Service
  redis_cache:
    image: redis:7-alpine
    container_name: workshop_redis_cache
    restart: unless-stopped
    volumes:
      - redis_cache_data:/data
    networks:
      - workshop_network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Redis Queue Service
  redis_queue:
    image: redis:7-alpine
    container_name: workshop_redis_queue
    restart: unless-stopped
    volumes:
      - redis_queue_data:/data
    networks:
      - workshop_network
    command: redis-server --appendonly yes

  # Universal Workshop ERP Service
  workshop_erp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshop_erp
    restart: unless-stopped
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-universal_workshop}
      - DB_USER=${DB_USER:-frappe}
      - DB_PASSWORD=${DB_PASSWORD:-frappe}
      - REDIS_CACHE_URL=redis://redis_cache:6379
      - REDIS_QUEUE_URL=redis://redis_queue:6379
      - SITE_NAME=${SITE_NAME:-workshop.local}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - LANG=${LANG:-ar}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-}
    volumes:
      - workshop_sites:/home/frappe/frappe-bench/sites
      - workshop_logs:/home/frappe/frappe-bench/logs
      - ./apps/universal_workshop:/home/frappe/frappe-bench/apps/universal_workshop
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - workshop_network
    depends_on:
      - mariadb
      - redis_cache
      - redis_queue
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/method/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: workshop_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./ssl:/etc/nginx/ssl
      - workshop_sites:/var/www/html:ro
    networks:
      - workshop_network
    depends_on:
      - workshop_erp
    profiles:
      - production

  # Backup Service
  backup:
    image: alpine:latest
    container_name: workshop_backup
    restart: "no"
    environment:
      - DB_HOST=mariadb
      - DB_NAME=${DB_NAME:-universal_workshop}
      - DB_USER=${DB_USER:-frappe}
      - DB_PASSWORD=${DB_PASSWORD:-frappe}
      - BACKUP_RETENTION_DAYS=${BACKUP_RETENTION_DAYS:-7}
    volumes:
      - workshop_backups:/backups
      - workshop_sites:/sites:ro
      - ./scripts/backup.sh:/backup.sh
    networks:
      - workshop_network
    depends_on:
      - mariadb
    profiles:
      - backup
    command: /bin/sh /backup.sh

volumes:
  mariadb_data:
    driver: local
  redis_cache_data:
    driver: local
  redis_queue_data:
    driver: local
  workshop_sites:
    driver: local
  workshop_logs:
    driver: local
  workshop_backups:
    driver: local

networks:
  workshop_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
